"""Add fecha_actualizacion to Producto

Revision ID: 5d886f944ea1
Revises: fefe0ccdf1cf
Create Date: 2025-04-29 23:33:10.245167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d886f944ea1'
down_revision = 'fefe0ccdf1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'fecha_actualizacion')
    # ### end Alembic commands ###
