"""Add nombre and apellido to User model

Revision ID: a7fc4d0f49c8
Revises: 1a180b21ac91
Create Date: 2025-04-28 11:56:56.338468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fc4d0f49c8'
down_revision = '1a180b21ac91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nombre', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('apellido', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'apellido')
    op.drop_column('user', 'nombre')
    # ### end Alembic commands ###
